
/'Clases'/
class Juego
class Aparencia
abstract Character
abstract Bloque
class Personaje

/' Relaciones '/

Juego "1" *-- "*" Character


Character *-- Aparencia
Character <|-- Personaje

Bloque *-- Aparencia